batch_size: 16
bidirectional: false
ckpt: ../../ckpt/sax/sax_model.pth
resume_step: 39000
crepe: full
experiment_name: Sax_DDSP
f0_threshold: 0.5
frame_resolution: 0.004
gpu: 0
gru_units: 512
loss: mss
lr: 0.001
lr_decay: 0.98
lr_min: 1.0e-07
lr_scheduler: multi
metric: mss
mlp_layers: 3
mlp_units: 512
n_fft: 2048
n_freq: 65
n_harmonics: 101
n_mels: 128
n_mfcc: 30
num_step: 100000
num_workers: 4
optimizer: radam
resume: true
sample_rate: 16000
seed: 940513
tensorboard_dir: ../tensorboard_log/
test: ../data/sax/test/
train: ../data/sax/train/
use_reverb: true
use_z: false
valid_waveform_sec: 12
validation_interval: 1000
waveform_sec: 1
z_units: 16